name: Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Say Hello
      run: echo "Hello world!"
    - name: Second step
      run: uname -a
      run: ls -l /
      
